name: ${project.name}
version: ${project.version}
main: ${groupId}.${artifactId}
api-version: '1.21'
authors: [euj3ne]
description: ${project.description}
website: ${project.url}
depend: []
softdepend: []
commands:
  spawn:
    description: Teleport to spawn
    usage: /spawn [player]
  setspawn:
    description: Set spawn to your location
    usage: /setspawn
permissions:
  isetspawn.spawn:
    description: Allows using /spawn
    default: op
  isetspawn.spawn.others:
    description: Allows using /spawn on other players
    default: op
  isetspawn.setspawn:
    description: Allows using /setspawn
    default: op
